# Generated by Django 6.0.3 on 2026-08-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contribution_budgettransaction_departmentbudget'),
        ('expenses', '0009_remove_expenserequest_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='budget_choice',
            field=models.CharField(choices=[('BK', 'BK'), ('CONTRIBUTION', 'Contribution'), ('MK', 'MK')], default='BK', max_length=20),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='budget_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contribution'),
        ),
    ]
