services:
  - type: web
    name: retirement-and-expenses-system
    env: python
    pythonVersion: "3.12.10"
    plan: free
    rootDir: .
    buildCommand: python -m pip install -r requirements.txt
    releaseCommand: cd matoleo_system && python manage.py migrate --noinput && python manage.py ensure_admin && python manage.py collectstatic --noinput --clear
    startCommand: cd matoleo_system/matoleo_system && gunicorn wsgi:application --workers 3 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://retirement-and-expenses-system.onrender.com"
      - key: DATABASE_URL
        value: "postgresql://matumiz_db_user:YcCbxXN6L96YQwWK0Qc9k7hoCeJQPcqN@dpg-d9seajajnfac739biogg-a/matumiz_db"
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        value: "MKJ"
      - key: ADMIN_PASSWORD
        value: "Hot@2000"
      - key: ADMIN_EMAIL
        value: "hotmass81@gmail.com"

databases:
  - name: matumiz_db
    type: postgresql
    plan: free
    databaseName: matumiz_db
    user: matumiz_db_user
